# Generated by Django 4.2.2 on 2023-07-07 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_cake',
            old_name='image',
            new_name='photo',
        ),
    ]
